const ARTIST_ID_FIELD = "artist-id"
const ILLUST_DATE_FIELD = "illust-date"
const ARTIST_NAME_FIELD = "artist-name"
const TAGS_TEXTAREA = "tags"
const IMAGES_FIELDSET = "images"
const IMAGE_CHECKBOX = "image"
